name: NancyNardi
favicon: null
layout_spectrum: 0.25733
typography_spectrum: 0.73737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9faf4'
    - '#184b5c'
    - '#c0c4ad'
    - '#629ba8'
    - '#8f5a37'
  brandStrength: 0.5
  lightness: 0.7157817350234836
  saturation: 0.01866800943389535
  rhythmicContrast: 0.6435194562654942
purpose: []
